### ISSUE TITLE
Branch model is confusing

### ISSUE THREAD

**Issue by roechi** [idealo/idealo.github.io#39]
Currently, we're treating the `develop` branch as our main branch. Which is confusing: not only is the name misleading, there is also a `master` branch which has an entirely unrelated history. 

As far as I understand, this `master` branch was actually the source branch which held the assets for the Github Pages deployment. We are now using the branch `gh-pages` for this purpose.

Hence I would recommend removing the branch `master` entirely and renaming the branch `develop` to `main`.

**Comment by conradkirschner** [comment]
yeah, I would delete `master` branch and use a branch name that reflects what it does. 

main -> main entry for checkout & dev starting point
publish/gh-pages -> identify for published content 

I see that it is already there the gh-pages branch. :) 

`master` can be deleted

**Comment by marcus-j** [comment]
Go for it, @roechi!

**Comment by roechi** [comment]
Ok, then I will rename `develop` -> `main` and remove `master`.

**Comment by roechi** [comment]
Everyone, make sure to update you local clone: 
```bash
git branch -m develop main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
